Feature/ldap auth
CHDR-Inventory-System/server pull request #15
Opened 2022-01-28 16:34 UTC by Jcherisma

2022-01-30 00:35 UTC, ctcuff requested changes
Works great, nice job! A few issues to be addressed then should be good to go. On a side a few formatting fixes:

- Just to stay consistent with the existing codebase, it's not necessary to add an underscore to the end of a variable name 👍.
- When using `create_error_response`, it's usually a good idea to give a descriptive error message so it's easier to debug server errors,

2022-01-30 00:35 UTC, ctcuff commented on src/models/inventory_item.py
> +class InventoryItem:
This file is from an older version of the repo so it can be deleted (along with the `models` folder too!)

2022-01-30 00:35 UTC, ctcuff commented on src/util/response_util.py
> +from flask import jsonify
This file is also from an older version of the repo so it can be deleted (this was renamed to `response.py`)

2022-01-30 00:35 UTC, ctcuff commented on src/routes/users.py
> +            {"Full Name": full_name, "nid": nid_, "email": email_, "created": created_}
Should be `fullName` here we'll also need a bit more data from this response. It should look like:
```json
{
    "ID": "id here",
    "created": "created here",
    "email": "email here",
    "role": "role here"
    "nid": "nid here",
    "fullName": "name here"
}
```

There's also a small bug here, lines 208 - 211 try to access data from the cursor while line 221 checks if the data from the cursor exists. That means if the cursor returns null, this will throw an error.

2022-01-30 00:35 UTC, ctcuff commented on src/routes/users.py
> +            return create_error_response("Please enter all required fields!", 204)
`2XX` codes usually mean success so we'll need to return some type of `4XX` error code

2022-01-30 00:35 UTC, ctcuff commented on src/routes/users.py
> +            return create_error_response("Please enter the required fields!", 204)
(Same comment as previous response code)

2022-01-30 00:35 UTC, ctcuff commented on src/routes/users.py
> +                cursor.execute("SELECT * FROM users WHERE nid = %s", (ucf_creds_nid,))
After the string ends, should be a percent instead of a comma, so essentially:
```python
cursor.execute('statement' % (variables,))
```

2022-01-30 00:35 UTC, ctcuff commented on src/routes/users.py
> +                        identity={"id": exist_acc["ID"], "role": exist_acc["role"]}
Just to be consistent with the naming in the database, `id` should be `ID`

2022-02-01 20:44 UTC, Jcherisma commented on src/models/inventory_item.py
> +class InventoryItem:
done.

2022-02-01 20:44 UTC, Jcherisma commented on src/util/response_util.py
> +from flask import jsonify
done.

2022-02-01 20:55 UTC, Jcherisma commented on src/routes/users.py
> +                        identity={"id": exist_acc["ID"], "role": exist_acc["role"]}
Done

2022-02-01 21:03 UTC, Jcherisma commented on src/routes/users.py
> +            return create_error_response("Please enter the required fields!", 204)
Done

2022-02-01 21:03 UTC, Jcherisma commented on src/routes/users.py
> +            return create_error_response("Please enter all required fields!", 204)
Done

2022-02-02 01:24 UTC, Jcherisma commented on src/routes/users.py
> +            {"Full Name": full_name, "nid": nid_, "email": email_, "created": created_}
Done

2022-02-02 01:25 UTC, Jcherisma commented on src/routes/users.py
> +                cursor.execute("SELECT * FROM users WHERE nid = %s", (ucf_creds_nid,))
Done

2022-02-02 18:10 UTC, ctcuff requested changes
Nice work on this, almost there, just a few things to address

2022-02-02 18:10 UTC, ctcuff commented on src/routes/users.py
> +            return create_error_response("User does not exist", 404)
Careful here, you'll want to check if `exist_acc` is not `None` before you try to access it, otherwise you'll get a `NoneType` error.

2022-02-02 18:10 UTC, ctcuff commented on src/routes/users.py
> +            }
This is definitely gonna be a helpful API response. Here, you just need to add the `verified` field. It's stored as a number in the database so make sure you convert it to a boolean first!

2022-02-02 18:10 UTC, ctcuff commented on src/routes/users.py
> +    query = "SELECT ID, fullName, nid, email, role, created FROM users"
This should also grab `verified` as well

2022-02-02 18:10 UTC, ctcuff commented on src/routes/users.py
> +                        identity={"ID": exist_acc["ID"], "role": exist_acc["role"]}
Here, we'll need to return a response that looks like:
```json
{
    "ID": "id here",
    "created": "created here",
    "email": "email here",
    "role": "role here"
    "nid": "nid here",
    "fullName": "name here",
    "verified": "boolean here"
    "token": "jwt here"
}
```
that way front end and mobile can store the JWT on their end.

2022-02-02 21:05 UTC, Jcherisma commented on src/routes/users.py
> +            return create_error_response("User does not exist", 404)
Done.

2022-02-02 21:26 UTC, Jcherisma commented on src/routes/users.py
> +    query = "SELECT ID, fullName, nid, email, role, created FROM users"
Done

2022-02-02 21:26 UTC, Jcherisma commented on src/routes/users.py
> +            }
Done

2022-02-02 21:35 UTC, Jcherisma commented on src/routes/users.py
> +                        identity={"ID": exist_acc["ID"], "role": exist_acc["role"]}
Done

2022-02-03 02:53 UTC, ctcuff approved these changes

2022-02-03 02:54 UTC, merged