Experimental/email
CHDR-Inventory-System/server pull request #22
Opened 2022-02-12 19:25 UTC by Jcherisma

2022-02-12 22:11 UTC, ctcuff requested changes
Great job on this! Just a few comments below.

Also, a quick note on styling, it's usually a good idea to stick to the `snake_casing` name convention when working in Python. For example, `update_verification` rather than `updateVerification`.

2022-02-12 22:11 UTC, ctcuff commented on src/routes/users.py
> +        if bcrypt.checkpw(password.encode("utf-8"), hash_pwrd.encode("utf-8")):
See the previous comment about the `if/else` structure, but this will throw an error if the passwords don't match because this function won't return a value

2022-02-17 20:33 UTC, AshenSilverwolf commented on src/routes/users.py
> +            return create_error_response("User does not exist", 404)
I feel like this should resolve as a 500 INTERNAL SERVER ERROR of some kind since the issue is that our system failed to insert the new user creds into the table. The user won't understand why they're getting an error saying "User doesn't exist" when they were trying to register for an account.

2022-02-17 20:38 UTC, AshenSilverwolf commented on src/routes/users.py
> +@users_blueprint.route("/verify/<user_id>/<uniquecode>", methods=["GET"])
I feel this should be a PATCH request since we're updating user information, not simply retrieving it.

2022-02-20 23:29 UTC, Jcherisma commented on src/routes/users.py
> +    except KeyError as err:
done.

2022-02-20 23:29 UTC, Jcherisma commented on src/routes/users.py
> +                "An account with this email or nid already exists", 409
Done.

2022-02-20 23:40 UTC, Jcherisma commented on src/routes/users.py
> +@users_blueprint.route("/verify/<user_id>/<uniquecode>", methods=["GET"])
We're retrieving it from the email that is sent, once it is clicked by the user.

2022-02-22 02:06 UTC, ctcuff approved these changes
Added a few tiny stylistic changes but LGTM!

2022-02-22 02:06 UTC, merged