Experience/scheduler2
CHDR-Inventory-System/server pull request #29
Opened 2022-03-28 20:00 UTC by Jcherisma

2022-03-28 20:04 UTC, Jcherisma commented
I have the scheduler running every minute, so change to your liking to test. However, we will have it running every 23 Hours When we hand it over, once we merge or prior we would have to test it out on the chdr server by sending an email out every 23 hours.

2022-03-31 01:38 UTC, ctcuff requested changes
Just a few comments below, also (slight nitpick), you'll wanna remove the calls to `print` since that seems to be leftover from debugging.

2022-03-31 01:38 UTC, ctcuff commented on src/app.py
>  app.register_blueprint(inventory_blueprint, url_prefix="/api/inventory")
This should still be `reservations` since that's what the client and mobile app expect

2022-03-31 01:38 UTC, ctcuff commented on src/background_tasks/notification.py
> +        if item_moveable == 1 & (reservation_status == "Checked Out"):
Think you might want the `and` operator here?

2022-03-31 01:38 UTC, ctcuff commented on src/background_tasks/notification.py
> +
You don't actually need to create a new cursor here, you can re-use the old `cursor` variable

2022-04-20 23:38 UTC, ctcuff approved these changes

2022-04-21 00:50 UTC, merged